### PR TITLE
Add umd build; fixes #354

### LINKED ISSUE #354: create umd dist build - for webpack aliasing
this is useful when creating aliases to improve webpack

http://survivejs.com/webpack/developing-with-webpack/optimizing-development/

### PR DESCRIPTION
**Pull request by Dattaya**

### CODE REVIEW

**Comment by Dattaya** [comment]
May I send a PR to github.com/cdnjs/cdnjs ?

**Comment by timdorr** [comment]
I'll get this out as a 4.0.3 soon.

**Comment by Dattaya** [comment]
Thank you, @timdorr for merging it! I'll send a PR to cdnjs withing a few days. Redux and react-router are already there.

**Comment by Dattaya** [comment]
> I'll send a PR to cdnjs withing a few days. Redux and react-router are already there.

Done—https://cdnjs.com/libraries/react-router-redux

**Pull request merged**
