### PR TITLE
Fix ie8 compatibility issue

### LINKED ISSUE #382: Fix IE8 Compatibility
Ref #379

Right now, as bundled via Babel 6, our named exports (`export foo from './foo'`) generate code that breaks in OldIE (at least IE8). There is a pending bug open with Babel to fix this: https://phabricator.babeljs.io/T7322

### PR DESCRIPTION
**Pull request by andyhu**
Fix #382

### CODE REVIEW

**Comment by timdorr** [comment]
You shouldn't be using this in production. This is primarily for dev tools support only. I don't think anyone is actively developing on ie8.

**Comment by andyhu** [comment]
But it doesn't hurt to merge it right? There's nothing to lose by supporting IE8?

**Comment by mjrussell** [comment]
> You shouldn't be using this in production.

@timdorr Im not sure I would agree with that statement. Even if you aren't using `syncHistoryToStore`, it seems perfectly legitimate to use `routerMiddleware` to dispatch history actions in production.

**Comment by timdorr** [comment]
We only have those as a convenience. I'm planning on removing them in the next release to encourage users to use the history singletons in React Router instead.

**Pull request closed without merging**
